development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:89637ecf507961bae2397235cde1aa24@tetra.redistogo.com:9281/
  channel_prefix: pingr_rb_production
